// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70w8lAKpaI-W2Qz2psBl4N11ydzuq_as',
    appId: '1:1098103696943:web:9010a2dc78ff62f85660da',
    messagingSenderId: '1098103696943',
    projectId: 'growk-v2',
    authDomain: 'growk-v2.firebaseapp.com',
    storageBucket: 'growk-v2.firebasestorage.app',
    measurementId: 'G-2EVSR11KPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDerN1Zd-4tMkiORTHe5wciYWGeeTaP4NQ',
    appId: '1:1098103696943:android:7da3f80a7ae3a0ce5660da',
    messagingSenderId: '1098103696943',
    projectId: 'growk-v2',
    storageBucket: 'growk-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDqfcwz56kY7a-oZuHT4sYiRqDaFy0kdY',
    appId: '1:1098103696943:ios:2f29401827f0cc0a5660da',
    messagingSenderId: '1098103696943',
    projectId: 'growk-v2',
    storageBucket: 'growk-v2.firebasestorage.app',
    iosBundleId: 'com.its.growkV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDqfcwz56kY7a-oZuHT4sYiRqDaFy0kdY',
    appId: '1:1098103696943:ios:2f29401827f0cc0a5660da',
    messagingSenderId: '1098103696943',
    projectId: 'growk-v2',
    storageBucket: 'growk-v2.firebasestorage.app',
    iosBundleId: 'com.its.growkV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA70w8lAKpaI-W2Qz2psBl4N11ydzuq_as',
    appId: '1:1098103696943:web:fa231067eea7dd535660da',
    messagingSenderId: '1098103696943',
    projectId: 'growk-v2',
    authDomain: 'growk-v2.firebaseapp.com',
    storageBucket: 'growk-v2.firebasestorage.app',
    measurementId: 'G-ZBVWSQQ2L8',
  );
}
